"use client";
import { useEffect, useState } from "react";
import { apiGet, apiPost } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-96 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
const sample = `contract BridgeExample {\n  function verify(bytes memory signature) external { /* signature flow */ }\n  function lzReceive(bytes calldata payload) external { /* crosschain message */ }\n}`;
export function CrossChainScannerClient() {
  const [status, setStatus] = useState<any>(null);
  const [chainFamily, setChainFamily] = useState("evm");
  const [chains, setChains] = useState("ethereum,polygon,base");
  const [source, setSource] = useState(sample);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(()=>{ apiGet<any>("/cross-chain/status").then(setStatus).catch(e=>setError(e.message)); },[]);
  async function run() { setError(null); try { const data = await apiPost<any>("/cross-chain/scan", { chain_family: chainFamily, chains: chains.split(",").map(x=>x.trim()).filter(Boolean), source_code: source, project_name: "RAADHANEX cross-chain review", real_only_acknowledged: true }); setResult(data); } catch(e) { setError(e instanceof Error ? e.message : "Cross-chain scan failed"); } }
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Cross-chain Support Scanner</h1><p className="mt-4 max-w-3xl text-slate-400">Real static/checklist hints for EVM multi-chain, Solana Anchor, and Move/Sui/Aptos readiness. No wallet connect, no transaction signing, no fake chain-specific audit.</p>{error && <p className="mt-6 rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="card p-5 space-y-4"><label className="block text-sm text-slate-300">Chain family<select className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={chainFamily} onChange={e=>setChainFamily(e.target.value)}><option value="evm">EVM</option><option value="solana_anchor">Solana Anchor checklist</option><option value="move_sui_aptos">Move/Sui/Aptos checklist</option></select></label><label className="block text-sm text-slate-300">Chains CSV<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={chains} onChange={e=>setChains(e.target.value)} /></label><label className="block text-sm text-slate-300">Source / ABI / architecture notes<textarea className="mono mt-2 h-72 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-xs text-white" value={source} onChange={e=>setSource(e.target.value)} /></label><button onClick={run} className="btn-primary w-full">Run cross-chain readiness scan</button></div><div className="space-y-5"><div className="card p-5"><p className="font-black text-white">Status</p>{status ? <JsonBlock value={status} /> : <p className="text-slate-400">Loading...</p>}</div>{result && <div className="card p-5"><p className="font-black text-white">Scan result</p><JsonBlock value={result} /></div>}</div></div></div>;
}
