import Link from "next/link";

const sample = `// Sample only — paste into scanner to generate a real local rule-engine result
pragma solidity ^0.8.0;
contract DemoVault {
    mapping(address => uint256) public balances;
    address public owner;
    function withdraw() public {
        (bool ok,) = msg.sender.call{value: balances[msg.sender]}("");
        require(ok);
        balances[msg.sender] = 0;
    }
    function adminDrain(address payable to) public {
        require(tx.origin == owner);
        selfdestruct(to);
    }
}`;

export function HomeScannerDemo() {
  return (
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="card grid gap-8 p-6 lg:grid-cols-[1fr_0.9fr] lg:p-8">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan">Real scanner demo path</p>
          <h2 className="mt-2 text-3xl font-black">Try a sample vulnerable contract, then replace with your real code.</h2>
          <p className="mt-3 text-slate-400">This homepage does not show fake live scan numbers. The sample below is only starter input; real findings are generated on the scanner page by backend rule/tool engines.</p>
          <pre className="mt-5 max-h-[360px] overflow-auto rounded-2xl border border-white/10 bg-black/40 p-4 text-xs leading-5 text-slate-200"><code>{sample}</code></pre>
        </div>
        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
          <h3 className="text-xl font-black">What is real in this demo?</h3>
          <ul className="mt-4 space-y-3 text-sm text-slate-300">
            <li>• Rule-engine findings are generated by backend code, not fake cards.</li>
            <li>• Slither/Aderyn/Semgrep run only if installed and enabled.</li>
            <li>• Missing modules show Not assessed / Tool Not Installed.</li>
            <li>• No certified audit or 100% secure claim.</li>
          </ul>
          <div className="mt-6 grid gap-3">
            <Link className="btn-primary" href="/scanner">Open scanner</Link>
            <Link className="btn-secondary" href="/feature-status">View real feature status</Link>
          </div>
        </div>
      </div>
    </section>
  );
}
