"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE } from "@/lib/api";
import { loadLatestUnifiedScan } from "@/lib/latestUnifiedScan";
import type { CombinedLaunchReport, UnifiedModuleCard, UnifiedUrlScanResponse } from "@/lib/types";

type ExportFormat = "pdf" | "html" | "markdown" | "json";

const reportSections = [
  ["Real scan data", "Uses the backend combined report generated by the latest unified scan."],
  ["Evidence gaps", "Not Assessed, Tool Not Installed, Provider Not Configured, and Manual states remain visible."],
  ["Paid path", "₹999 pilot validation never unlocks automatically without backend/manual payment verification."],
  ["Export formats", "PDF, HTML, Markdown, and JSON export from a real report_hash only."],
];

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function formatDate(value?: string | null) {
  if (!value) return "—";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return parsed.toLocaleString();
}

function formatName(format: ExportFormat) {
  return format === "markdown" ? "MD" : format.toUpperCase();
}

function extensionFor(format: ExportFormat) {
  return format === "markdown" ? "md" : format;
}

function statusClass(value?: string | null) {
  const text = (value || "").toLowerCase();
  if (text.includes("ready") || text.includes("low")) return "badge-green";
  if (text.includes("high") || text.includes("critical") || text.includes("manual") || text.includes("missing")) return "badge-amber";
  return "badge-slate";
}

function scoreText(score?: number | null) {
  return typeof score === "number" ? `${score}/100` : "Not Assessed";
}

function missingCards(cards: UnifiedModuleCard[]) {
  return cards.filter((card) => !card.assessed || card.required_input.length > 0);
}

function exportReadyReport(result: UnifiedUrlScanResponse | null): CombinedLaunchReport | null {
  if (!result?.combined_report?.report_id || !result.combined_report.report_hash) return null;
  return result.combined_report;
}

export function ReportCenterClient() {
  const [result, setResult] = useState<UnifiedUrlScanResponse | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [status, setStatus] = useState("Report export requires a real scan result with report_hash.");
  const [busy, setBusy] = useState<ExportFormat | null>(null);

  useEffect(() => {
    setResult(loadLatestUnifiedScan());
    setLoaded(true);
  }, []);

  const report = exportReadyReport(result);
  const gaps = useMemo(() => missingCards(result?.module_cards ?? []), [result]);
  const hasVerifiedReport = Boolean(report);

  async function exportReport(format: ExportFormat) {
    if (!report) {
      setStatus("Run a real scan first. Export is blocked because no combined report_hash is available.");
      return;
    }
    setBusy(format);
    setStatus(`Preparing ${formatName(format)} from real report data...`);
    const accept = format === "pdf" ? "application/pdf" : format === "html" ? "text/html" : format === "markdown" ? "text/markdown" : "application/json";
    try {
      const response = await fetch(`${API_BASE}/report/export/${format}`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: accept },
        body: JSON.stringify({ report }),
      });
      if (!response.ok) {
        const detail = await response.text();
        throw new Error(detail || "Export failed");
      }
      const blob = await response.blob();
      downloadBlob(blob, `${report.report_id}.${extensionFor(format)}`);
      setStatus(`${formatName(format)} exported from report ${report.report_id}. Keep pre-audit disclaimers visible when sharing.`);
    } catch (error) {
      setStatus(error instanceof Error ? error.message : "Export failed.");
    } finally {
      setBusy(null);
    }
  }

  if (!loaded) {
    return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="card p-6 text-slate-300">Loading report center...</div></main>;
  }

  return (
    <main className="report-final-page mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
      <div className="report-clean-actions">
        <Link href="/scanner/unified-url" className="btn-primary">Run scan →</Link>
        <Link href="/results" className="btn-secondary">Latest results</Link>
        <Link href="/payment-validation" className="btn-secondary">₹999 validation</Link>
        <Link href="/dashboard/scans" className="btn-secondary">Saved scans</Link>
      </div>

      <section className="mt-6 rounded-[1.5rem] border border-cyan-300/15 bg-cyan-300/[0.04] p-6 shadow-2xl shadow-black/20">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="section-label">Report center</p>
            <h1 className="mt-2 text-3xl font-black text-white">{result ? result.project_name || result.website_url : "No active report selected"}</h1>
            <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-300">
              {result ? "This report center is connected to your latest real unified scan output." : "Run a scan or open a saved scan first. This page does not show fake sample reports."}
            </p>
          </div>
          <span className={`badge ${hasVerifiedReport ? "badge-green" : "badge-amber"}`}>{hasVerifiedReport ? "Export ready" : "Needs scan data"}</span>
        </div>

        {result ? (
          <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Report ID</p><p className="mt-2 truncate text-sm font-black text-white">{report?.report_id || result.report_id}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Generated</p><p className="mt-2 text-sm font-black text-white">{formatDate(result.generated_at)}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Available score</p><p className="mt-2 text-sm font-black text-white">{scoreText(result.available_score)}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Risk</p><p className="mt-2 text-sm font-black text-white">{result.risk_label || "Partial readiness"}</p></div>
          </div>
        ) : null}
      </section>

      <section className="mt-5 grid gap-4 lg:grid-cols-4">
        {reportSections.map(([title, text]) => (
          <article key={title} className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
            <h2 className="text-xl font-black text-white">{title}</h2>
            <p className="mt-3 text-sm leading-7 text-slate-300">{text}</p>
          </article>
        ))}
      </section>

      <section className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_0.95fr]">
        <article className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="section-label">Exports</p>
              <h2 className="mt-2 text-2xl font-black text-white">Download real report data</h2>
              <p className="mt-2 text-sm leading-7 text-slate-300">Exports call the backend `/report/export/*` endpoints with the real combined report payload. If report_hash is missing, export stays blocked.</p>
            </div>
            <span className={`badge ${statusClass(report?.combined?.risk_label || result?.risk_label)}`}>{report?.combined?.risk_label || result?.risk_label || "Not Assessed"}</span>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {(["pdf", "html", "markdown", "json"] as ExportFormat[]).map((format) => (
              <button key={format} className="btn-secondary" onClick={() => void exportReport(format)} disabled={busy !== null || !hasVerifiedReport}>
                {busy === format ? "Exporting..." : `Export ${formatName(format)}`}
              </button>
            ))}
          </div>
          <p className={`mt-5 rounded-2xl border p-4 text-sm leading-7 ${hasVerifiedReport ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-100" : "border-amber-300/20 bg-amber-300/10 text-amber-100"}`}>{status}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link href="/report/professional" className="btn-ghost">Open advanced export builder</Link>
            <Link href="/payment-validation" className="btn-ghost">Validate ₹999 pilot payment</Link>
          </div>
        </article>

        <article className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
          <p className="section-label">Pilot report flow</p>
          <h2 className="mt-2 text-2xl font-black text-white">₹999 path stays honest</h2>
          <p className="mt-3 text-sm leading-7 text-slate-300">Payment creates a validation workflow only. Report/export access must be verified by Razorpay webhook or manual backend/admin validation. No fake success state is added here.</p>
          <div className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/10 p-4 text-sm leading-7 text-amber-50">
            <strong>Blocked:</strong> certified audit claim, 100% secure claim, “all vulnerabilities found”, fake payment success, or fake manual review.
          </div>
        </article>
      </section>

      <section className="mt-5 rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
        <p className="section-label">Evidence gaps</p>
        <h2 className="mt-2 text-2xl font-black text-white">What remains before delivery</h2>
        {gaps.length ? (
          <div className="mt-5 grid gap-3 lg:grid-cols-2">
            {gaps.map((card) => (
              <article key={card.module} className="rounded-2xl border border-white/[0.07] bg-black/20 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h3 className="font-black text-white">{card.label}</h3>
                    <p className="mt-1 text-xs uppercase tracking-[0.14em] text-slate-500">{card.status}</p>
                  </div>
                  <span className={`badge ${statusClass(card.status)}`}>{card.assessed ? "Partial" : "Gap"}</span>
                </div>
                <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-300">
                  {(card.required_input.length ? card.required_input : card.limitations).slice(0, 4).map((item) => <li key={item}>• {item}</li>)}
                </ul>
              </article>
            ))}
          </div>
        ) : <p className="mt-4 text-sm leading-7 text-slate-400">No missing modules were reported in the latest scan payload.</p>}
      </section>
    </main>
  );
}
