"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { API_BASE } from "@/lib/api";
import { loadLatestUnifiedScan } from "@/lib/latestUnifiedScan";
import type { CombinedLaunchReport, UnifiedModuleCard, UnifiedUrlScanResponse } from "@/lib/types";

type ExportFormat = "pdf" | "html" | "markdown" | "json";

const reportSections = [
  ["Real scan data", "Uses the backend combined report generated by the latest unified scan."],
  ["Evidence gaps", "Not Assessed, Tool Not Installed, Provider Not Configured, and Manual states remain visible."],
  ["Paid path", "₹999 pilot validation never unlocks automatically without backend/manual payment verification."],
  ["Export formats", "PDF, HTML, Markdown, and JSON export from a real report_hash only."],
];

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function formatDate(value?: string | null) {
  if (!value) return "—";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return parsed.toLocaleString();
}

function formatName(format: ExportFormat) {
  return format === "markdown" ? "MD" : format.toUpperCase();
}

function extensionFor(format: ExportFormat) {
  return format === "markdown" ? "md" : format;
}

function statusClass(value?: string | null) {
  const text = (value || "").toLowerCase();
  if (text.includes("ready") || text.includes("low")) return "badge-green";
  if (text.includes("high") || text.includes("critical") || text.includes("manual") || text.includes("missing")) return "badge-amber";
  return "badge-slate";
}


function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asRecord(value: unknown): Record<string, unknown> {
  return isRecord(value) ? value : {};
}

function asString(value: unknown, fallback = "—") {
  return typeof value === "string" && value.trim() ? value : fallback;
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function formatJson(value: unknown) {
  try { return JSON.stringify(value, null, 2); } catch { return String(value); }
}

function scoreText(score?: number | null) {
  return typeof score === "number" ? `${score}/100` : "Not Assessed";
}

function missingCards(cards: UnifiedModuleCard[]) {
  return cards.filter((card) => !card.assessed || card.required_input.length > 0);
}

function exportReadyReport(result: UnifiedUrlScanResponse | null): CombinedLaunchReport | null {
  if (!result?.combined_report?.report_id || !result.combined_report.report_hash) return null;
  const extras = result as unknown as { accuracy_upgrade?: unknown; detection_expansion?: unknown; bug_detection_coverage?: unknown; real_evidence_summary?: unknown };
  return {
    ...result.combined_report,
    json_export: {
      ...(result.combined_report.json_export || {}),
      accuracy_upgrade: extras.accuracy_upgrade ?? null,
      detection_expansion: extras.detection_expansion ?? null,
      bug_detection_coverage: extras.bug_detection_coverage ?? null,
      real_evidence_summary: extras.real_evidence_summary ?? null,
    },
  };
}

function BugCoverageReportCard({ result }: { result: UnifiedUrlScanResponse | null }) {
  const coverage = result?.bug_detection_coverage;
  if (!coverage) return null;
  const severity = coverage.by_severity || {};
  return (
    <section className="mt-5 rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="section-label">Phase 49 proof coverage</p>
          <h2 className="mt-2 text-2xl font-black text-white">Report-visible bug/proof coverage</h2>
          <p className="mt-2 text-sm leading-7 text-slate-300">{coverage.visibility_rule}</p>
        </div>
        <span className={`badge ${coverage.critical_high_count ? "badge-amber" : "badge-green"}`}>{coverage.total_findings_from_assessed_modules} finding(s)</span>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">
        <div className="rounded-2xl border border-red-400/20 bg-red-500/10 p-4"><p className="text-xs uppercase tracking-[0.16em] text-red-100">Proof bugs/exposures</p><p className="mt-2 text-2xl font-black text-white">{Number(coverage.confirmed_proof_exposure_count || 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Critical</p><p className="mt-2 text-2xl font-black text-white">{Number(severity.critical || 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">High</p><p className="mt-2 text-2xl font-black text-white">{Number(severity.high || 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Medium</p><p className="mt-2 text-2xl font-black text-white">{Number(severity.medium || 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Low</p><p className="mt-2 text-2xl font-black text-white">{Number(severity.low || 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Info</p><p className="mt-2 text-2xl font-black text-white">{Number(severity.info || 0)}</p></div>
      </div>
      <details className="mt-5 rounded-2xl border border-white/[0.07] bg-black/20 p-4 text-sm leading-6 text-slate-300">
        <summary className="cursor-pointer font-black text-white">Coverage added in this phase</summary>
        <ul className="mt-3 grid gap-2 md:grid-cols-2">{coverage.coverage_added.map((item) => <li key={item}>• {item}</li>)}</ul>
      </details>
    </section>
  );
}


function AccuracyUpgradeReportCard({ result }: { result: UnifiedUrlScanResponse | null }) {
  const accuracy = asRecord((result as unknown as { accuracy_upgrade?: unknown } | null)?.accuracy_upgrade);
  if (!Object.keys(accuracy).length) return null;
  const phases = Object.entries(asRecord(accuracy.phases));
  return (
    <section className="mt-5 rounded-[1.5rem] border border-cyan-300/15 bg-cyan-300/[0.04] p-5 shadow-2xl shadow-black/20">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="section-label">Phases 52–58 accuracy stack</p>
          <h2 className="mt-2 text-2xl font-black text-white">Report accuracy upgrade attached</h2>
          <p className="mt-2 text-sm leading-7 text-slate-300">{asString(accuracy.output_authenticity_guarantee, "Findings must be evidence-backed; missing coverage stays Not Assessed.")}</p>
        </div>
        <Link href="/accuracy-upgrade" className="btn-secondary">Open accuracy hub</Link>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {phases.map(([key, value]) => {
          const phase = asRecord(value);
          const state = asString(phase.state, "Not Assessed");
          const proofCount = asArray(phase.findings).length || asArray(phase.confirmed_simulation_findings).length || Number(asRecord(phase.osv).vulnerability_count || 0);
          return (
            <article key={key} className="rounded-2xl border border-white/[0.07] bg-black/20 p-4">
              <p className="text-xs uppercase tracking-[0.16em] text-slate-500">{key}</p>
              <h3 className="mt-2 font-black text-white">{asString(phase.engine, key)}</h3>
              <p className="mt-2 text-sm text-slate-300">State: <b>{state}</b></p>
              <p className="mt-1 text-sm text-slate-300">Proofs: <b>{proofCount}</b></p>
            </article>
          );
        })}
      </div>
      <details className="mt-5 rounded-2xl border border-white/[0.07] bg-black/20 p-4 text-sm leading-6 text-slate-300">
        <summary className="cursor-pointer font-black text-white">Raw accuracy package</summary>
        <pre className="mt-4 max-h-[360px] overflow-auto text-xs">{formatJson(accuracy)}</pre>
      </details>
    </section>
  );
}

function DetectionExpansionReportCard({ result }: { result: UnifiedUrlScanResponse | null }) {
  const expansion = asRecord((result as unknown as { detection_expansion?: unknown } | null)?.detection_expansion);
  if (!Object.keys(expansion).length) return null;
  const summary = asRecord(expansion.summary);
  const phases = Object.entries(asRecord(expansion.phases));
  return (
    <section className="mt-5 rounded-[1.5rem] border border-purple-300/15 bg-purple-300/[0.045] p-5 shadow-2xl shadow-black/20">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="section-label">Phases 60–67 deep coverage</p>
          <h2 className="mt-2 text-2xl font-black text-white">Deep detection expansion attached</h2>
          <p className="mt-2 text-sm leading-7 text-slate-300">{asString(expansion.real_only_rule, "Every finding needs real evidence or supplied artifacts.")}</p>
        </div>
        <Link href="/detection-expansion" className="btn-secondary">Open hub</Link>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Deep findings</p><p className="mt-2 text-2xl font-black text-white">{String(summary.total_findings ?? 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Critical/high</p><p className="mt-2 text-2xl font-black text-white">{String(summary.critical_high_findings ?? 0)}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Assessed phases</p><p className="mt-2 text-2xl font-black text-white">{String(summary.assessed_phase_count ?? "—")}</p></div>
        <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">High-confidence</p><p className="mt-2 text-2xl font-black text-white">{String(summary.confirmed_high_confidence_findings ?? 0)}</p></div>
      </div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {phases.map(([key, value]) => {
          const phase = asRecord(value);
          return (
            <article key={key} className="rounded-2xl border border-white/[0.07] bg-black/20 p-4">
              <p className="text-xs uppercase tracking-[0.16em] text-slate-500">{key}</p>
              <h3 className="mt-2 font-black text-white">{asString(phase.engine, key)}</h3>
              <p className="mt-2 text-sm text-slate-300">State: <b>{asString(phase.state, "Not Assessed")}</b></p>
              <p className="mt-1 text-sm text-slate-300">Findings: <b>{asArray(phase.findings).length}</b></p>
            </article>
          );
        })}
      </div>
    </section>
  );
}

export function ReportCenterClient() {
  const [result, setResult] = useState<UnifiedUrlScanResponse | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [status, setStatus] = useState("Report export requires a real scan result with report_hash.");
  const [busy, setBusy] = useState<ExportFormat | null>(null);

  useEffect(() => {
    setResult(loadLatestUnifiedScan());
    setLoaded(true);
  }, []);

  const report = exportReadyReport(result);
  const gaps = useMemo(() => missingCards(result?.module_cards ?? []), [result]);
  const hasVerifiedReport = Boolean(report);
  const pipeline = result?.findings_pipeline;
  const exportGateReady = Boolean(pipeline?.export_gate?.export_ready);
  const canExport = Boolean(report) && (!pipeline || (pipeline.pipeline_ready && exportGateReady));

  async function exportReport(format: ExportFormat) {
    if (!report) {
      setStatus("Run a real scan first. Export is blocked because no combined report_hash is available.");
      return;
    }
    if (pipeline && (!pipeline.pipeline_ready || !pipeline.export_gate.export_ready)) {
      setStatus("Export is blocked by Phase 45 pipeline validation. Fix pipeline blockers or rerun the scan before delivery.");
      return;
    }
    setBusy(format);
    setStatus(`Preparing ${formatName(format)} from real report data...`);
    const accept = format === "pdf" ? "application/pdf" : format === "html" ? "text/html" : format === "markdown" ? "text/markdown" : "application/json";
    try {
      const response = await fetch(`${API_BASE}/report/export/${format}`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: accept },
        body: JSON.stringify({ report }),
      });
      if (!response.ok) {
        const detail = await response.text();
        throw new Error(detail || "Export failed");
      }
      const blob = await response.blob();
      downloadBlob(blob, `${report.report_id}.${extensionFor(format)}`);
      setStatus(`${formatName(format)} exported from report ${report.report_id}. Keep pre-audit disclaimers visible when sharing.`);
    } catch (error) {
      setStatus(error instanceof Error ? error.message : "Export failed.");
    } finally {
      setBusy(null);
    }
  }

  if (!loaded) {
    return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="card p-6 text-slate-300">Loading report center...</div></main>;
  }

  return (
    <main className="report-final-page mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
      <div className="report-clean-actions">
        <Link href="/scanner/unified-url" className="btn-primary">Run scan →</Link>
        <Link href="/results" className="btn-secondary">Latest results</Link>
        <Link href="/payment-validation" className="btn-secondary">₹999 validation</Link>
        <Link href="/dashboard/scans" className="btn-secondary">Saved scans</Link>
      </div>

      <section className="mt-6 rounded-[1.5rem] border border-cyan-300/15 bg-cyan-300/[0.04] p-6 shadow-2xl shadow-black/20">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="section-label">Report center</p>
            <h1 className="mt-2 text-3xl font-black text-white">{result ? result.project_name || result.website_url : "No active report selected"}</h1>
            <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-300">
              {result ? "This report center is connected to your latest real unified scan output." : "Run a scan or open a saved scan first. This page does not show fake sample reports."}
            </p>
          </div>
          <span className={`badge ${hasVerifiedReport ? "badge-green" : "badge-amber"}`}>{hasVerifiedReport ? "Export ready" : "Needs scan data"}</span>
        </div>

        {result ? (
          <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Report ID</p><p className="mt-2 truncate text-sm font-black text-white">{report?.report_id || result.report_id}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Generated</p><p className="mt-2 text-sm font-black text-white">{formatDate(result.generated_at)}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Available score</p><p className="mt-2 text-sm font-black text-white">{scoreText(result.available_score)}</p></div>
            <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Risk</p><p className="mt-2 text-sm font-black text-white">{result.risk_label || "Partial readiness"}</p></div>
          </div>
        ) : null}
      </section>

      <section className="mt-5 grid gap-4 lg:grid-cols-4">
        {reportSections.map(([title, text]) => (
          <article key={title} className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
            <h2 className="text-xl font-black text-white">{title}</h2>
            <p className="mt-3 text-sm leading-7 text-slate-300">{text}</p>
          </article>
        ))}
      </section>

      <BugCoverageReportCard result={result} />
      <AccuracyUpgradeReportCard result={result} />
      <DetectionExpansionReportCard result={result} />

      <section className="mt-5 rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="section-label">Phase 45 export integrity</p>
            <h2 className="mt-2 text-2xl font-black text-white">Report uses real findings pipeline</h2>
            <p className="mt-2 text-sm leading-7 text-slate-300">Export should unlock only when the latest scan has combined report data, report_hash, and no pipeline blocker. Older saved scans may show “not attached” until rerun.</p>
          </div>
          <span className={`badge ${pipeline?.pipeline_ready && exportGateReady ? "badge-green" : "badge-amber"}`}>{pipeline?.pipeline_ready && exportGateReady ? "Pipeline export-ready" : "Needs validation"}</span>
        </div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Pipeline</p><p className="mt-2 text-sm font-black text-white">{pipeline?.status || "Not attached"}</p></div>
          <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Real findings</p><p className="mt-2 text-2xl font-black text-white">{pipeline?.summary.real_findings ?? "—"}</p></div>
          <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Tool status</p><p className="mt-2 text-2xl font-black text-white">{pipeline?.summary.tool_status_messages ?? "—"}</p></div>
          <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Blockers</p><p className="mt-2 text-2xl font-black text-white">{pipeline?.summary.blocker_count ?? "—"}</p></div>
          <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Report hash</p><p className="mt-2 text-sm font-black text-white">{pipeline?.export_gate.report_hash_present ? "Present" : hasVerifiedReport ? "Present" : "Missing"}</p></div>
        </div>
        {pipeline?.integrity?.issues?.length ? (
          <details className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/10 p-4 text-sm leading-6 text-amber-50">
            <summary className="cursor-pointer font-black text-white">Pipeline export issues</summary>
            <ul className="mt-3 space-y-2">{pipeline.integrity.issues.slice(0, 6).map((issue) => <li key={issue}>• {issue}</li>)}</ul>
          </details>
        ) : null}
      </section>

      <section className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_0.95fr]">
        <article className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="section-label">Exports</p>
              <h2 className="mt-2 text-2xl font-black text-white">Download real report data</h2>
              <p className="mt-2 text-sm leading-7 text-slate-300">Exports call the backend `/report/export/*` endpoints with the real combined report payload. If report_hash is missing, export stays blocked.</p>
            </div>
            <span className={`badge ${statusClass(report?.combined?.risk_label || result?.risk_label)}`}>{report?.combined?.risk_label || result?.risk_label || "Not Assessed"}</span>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {(["pdf", "html", "markdown", "json"] as ExportFormat[]).map((format) => (
              <button key={format} className="btn-secondary" onClick={() => void exportReport(format)} disabled={busy !== null || !canExport}>
                {busy === format ? "Exporting..." : `Export ${formatName(format)}`}
              </button>
            ))}
          </div>
          <p className={`mt-5 rounded-2xl border p-4 text-sm leading-7 ${hasVerifiedReport ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-100" : "border-amber-300/20 bg-amber-300/10 text-amber-100"}`}>{status}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link href="/report/professional" className="btn-ghost">Open advanced export builder</Link>
            <Link href="/payment-validation" className="btn-ghost">Validate ₹999 pilot payment</Link>
          </div>
        </article>

        <article className="rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
          <p className="section-label">Pilot report flow</p>
          <h2 className="mt-2 text-2xl font-black text-white">₹999 path stays honest</h2>
          <p className="mt-3 text-sm leading-7 text-slate-300">Payment creates a validation workflow only. Report/export access must be verified by Razorpay webhook or manual backend/admin validation. No fake success state is added here.</p>
          <div className="mt-5 rounded-2xl border border-amber-300/15 bg-amber-300/10 p-4 text-sm leading-7 text-amber-50">
            <strong>Blocked:</strong> certified audit claim, 100% secure claim, “all vulnerabilities found”, fake payment success, or fake manual review.
          </div>
        </article>
      </section>

      <section className="mt-5 rounded-[1.5rem] border border-white/10 bg-white/[0.035] p-5 shadow-2xl shadow-black/20">
        <p className="section-label">Evidence gaps</p>
        <h2 className="mt-2 text-2xl font-black text-white">What remains before delivery</h2>
        {gaps.length ? (
          <div className="mt-5 grid gap-3 lg:grid-cols-2">
            {gaps.map((card) => (
              <article key={card.module} className="rounded-2xl border border-white/[0.07] bg-black/20 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h3 className="font-black text-white">{card.label}</h3>
                    <p className="mt-1 text-xs uppercase tracking-[0.14em] text-slate-500">{card.status}</p>
                  </div>
                  <span className={`badge ${statusClass(card.status)}`}>{card.assessed ? "Partial" : "Gap"}</span>
                </div>
                <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-300">
                  {(card.required_input.length ? card.required_input : card.limitations).slice(0, 4).map((item) => <li key={item}>• {item}</li>)}
                </ul>
              </article>
            ))}
          </div>
        ) : <p className="mt-4 text-sm leading-7 text-slate-400">No missing modules were reported in the latest scan payload.</p>}
      </section>
    </main>
  );
}
