"use client";
import { useEffect, useState } from "react";
import { apiGet, apiPost } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-96 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
export function ComplianceScannerClient() {
  const [status, setStatus] = useState<any>(null);
  const [projectName, setProjectName] = useState("");
  const [jurisdictions, setJurisdictions] = useState("general_web3,india_vda,gdpr");
  const [flags, setFlags] = useState({ has_terms:false, has_privacy_policy:false, has_refund_policy:false, collects_personal_data:true, has_data_deletion_flow:false, handles_payments_in_inr:true, has_gst_invoice_flow:false, has_risk_disclosure:false, has_incident_response:false, has_bug_bounty_safe_harbor:false });
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(()=>{ apiGet<any>("/compliance/status").then(setStatus).catch(e=>setError(e.message)); },[]);
  async function run() { setError(null); try { const data = await apiPost<any>("/compliance/scan", { project_name: projectName, project_type: "web3_launch", jurisdictions: jurisdictions.split(",").map(x=>x.trim()).filter(Boolean), ...flags, real_only_acknowledged: true }); setResult(data); } catch(e) { setError(e instanceof Error ? e.message : "Compliance scan failed"); } }
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Compliance Readiness Scanner</h1><p className="mt-4 max-w-3xl text-slate-400">Checklist-based readiness for India VDA, GDPR, MiCA/FATF-style gaps. This is not legal advice; it flags missing policies/evidence for manual review.</p>{error && <p className="mt-6 rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="card p-5 space-y-4"><label className="block text-sm text-slate-300">Project name<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={projectName} onChange={e=>setProjectName(e.target.value)} /></label><label className="block text-sm text-slate-300">Jurisdictions CSV<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={jurisdictions} onChange={e=>setJurisdictions(e.target.value)} /></label><div className="grid gap-2 sm:grid-cols-2">{Object.entries(flags).map(([key,val])=><label key={key} className="rounded-xl border border-white/10 bg-white/[0.03] p-3 text-sm text-slate-300"><input type="checkbox" className="mr-2" checked={val} onChange={e=>setFlags({...flags,[key]:e.target.checked})}/>{key.replaceAll("_"," ")}</label>)}</div><button onClick={run} className="btn-primary w-full">Run compliance readiness scan</button></div><div className="space-y-5"><div className="card p-5"><p className="font-black text-white">Status</p>{status ? <JsonBlock value={status} /> : <p className="text-slate-400">Loading...</p>}</div>{result && <div className="card p-5"><p className="font-black text-white">Report</p><JsonBlock value={result} /></div>}</div></div></div>;
}
