"use client";
import { useState } from "react";
import { API_BASE } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-96 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
async function adminFetch(path: string, token: string, init?: RequestInit) { const response = await fetch(`${API_BASE}${path}`, { ...init, headers: { "X-Admin-Token": token, "Content-Type": "application/json", ...(init?.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Admin request failed"); return data; }
export function AdminSuperClient() {
  const [token, setToken] = useState("");
  const [data, setData] = useState<any>(null);
  const [flagKey, setFlagKey] = useState("github_action_beta");
  const [error, setError] = useState<string | null>(null);
  async function load(path: string) { setError(null); try { setData(await adminFetch(path, token)); } catch(e) { setError(e instanceof Error ? e.message : "Admin request failed"); } }
  async function updateFlag() { setError(null); try { setData(await adminFetch(`/admin/super/feature-flags/${encodeURIComponent(flagKey)}`, token, { method: "PATCH", body: JSON.stringify({ enabled: true, note: "Enabled from Admin Super Panel local test", actor: "local-admin", real_only_acknowledged: true }) })); } catch(e) { setError(e instanceof Error ? e.message : "Flag update failed"); } }
  return <div className="quantum-module-screen mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Admin Super Panel v2</h1><p className="mt-4 max-w-3xl text-slate-400">Admin-only overview calculated from real stored records. No fake MRR, no fake system metrics, no fake queue data.</p><div className="mt-8 grid gap-6 lg:grid-cols-[0.85fr_1.15fr]"><div className="card space-y-4 p-6"><label className="block text-sm font-bold text-slate-200">Admin token<input className="input mt-2" value={token} onChange={(e) => setToken(e.target.value)} placeholder="Backend ADMIN_TOKEN" /></label><div className="grid gap-3 sm:grid-cols-2"><button className="btn-primary" onClick={() => load("/admin/super/dashboard")}>Dashboard</button><button className="btn-secondary" onClick={() => load("/admin/super/system-health")}>System health</button><button className="btn-secondary" onClick={() => load("/admin/super/feature-flags")}>Feature flags</button><button className="btn-secondary" onClick={() => load("/admin/super/audit-log")}>Audit log</button></div><label className="block text-sm font-bold text-slate-200">Feature flag key<input className="input mt-2" value={flagKey} onChange={(e) => setFlagKey(e.target.value)} /></label><button className="btn-primary" onClick={updateFlag}>Enable/update flag</button>{error && <p className="rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}</div><div className="card p-6"><p className="font-black text-white">Admin response</p>{data ? <JsonBlock value={data} /> : <p className="mt-4 text-sm text-slate-400">Enter admin token and load a real admin endpoint.</p>}</div></div></div>;
}
