"use client";
import { useState } from "react";
import { apiGet, apiPatch, apiPost, API_BASE } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-80 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
export function DeveloperApiClient() {
  const [keyName, setKeyName] = useState("Local developer key");
  const [apiKey, setApiKey] = useState("");
  const [keys, setKeys] = useState<any[]>([]);
  const [code, setCode] = useState("// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\ncontract Demo { address owner; function withdraw() external { payable(msg.sender).transfer(address(this).balance); } }");
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  async function createKey() { setError(null); try { const data = await apiPost<any>("/developer-api/keys", { name: keyName, permissions: ["audit:start", "audit:read", "registry:verify", "threat:read"], rate_limit_per_hour: 60, real_only_acknowledged: true }); setApiKey(data.api_key); setResult(data); await listKeys(); } catch (err) { setError(err instanceof Error ? err.message : "Key creation failed"); } }
  async function listKeys() { const data = await apiGet<any>("/developer-api/keys"); setKeys(data.keys || []); }
  async function runApiAudit() { setError(null); try { const response = await fetch(`${API_BASE}/api/v1/audit`, { method: "POST", headers: { "Content-Type": "application/json", "X-Web3Guard-API-Key": apiKey }, body: JSON.stringify({ project_name: "Developer API Demo", solidity_code: code, real_only_acknowledged: true }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "API audit failed"); setResult(data); } catch (err) { setError(err instanceof Error ? err.message : "API audit failed"); } }
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Developer API + API Keys</h1><p className="mt-4 max-w-3xl text-slate-400">Create hashed API keys and call real API endpoints. API keys are shown once, then stored only as hashes. No SDK/webhook/live integration is faked.</p><div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="card space-y-4 p-6"><label className="block text-sm font-bold text-slate-200">API key name<input className="input mt-2" value={keyName} onChange={(e) => setKeyName(e.target.value)} /></label><div className="grid gap-3 sm:grid-cols-2"><button className="btn-primary" onClick={createKey}>Create API key</button><button className="btn-secondary" onClick={listKeys}>List key metadata</button></div>{apiKey && <div className="rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-50"><p className="font-bold">Copy now — shown once</p><p className="mono mt-2 break-all text-xs">{apiKey}</p></div>}<label className="block text-sm font-bold text-slate-200">Solidity code for API audit<textarea className="input mt-2 min-h-40" value={code} onChange={(e) => setCode(e.target.value)} /></label><button className="btn-primary" onClick={runApiAudit} disabled={!apiKey}>Run /api/v1/audit</button>{error && <p className="rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}</div><div className="space-y-5"><div className="card p-6"><p className="font-black text-white">Key metadata</p><div className="mt-4 space-y-3">{keys.length ? keys.map((k) => <div key={k.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="font-bold text-white">{k.name}</p><p className="text-xs text-slate-400">{k.id} • {k.key_prefix}… • {k.status}</p></div>) : <p className="text-sm text-slate-400">No key metadata loaded.</p>}</div></div>{result && <div className="card p-6"><p className="font-black text-white">Latest result</p><div className="mt-4"><JsonBlock value={result} /></div></div>}</div></div></div>;
}
