"use client";
import { useState } from "react";
import { apiGet, apiPost } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-80 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
export function PublicRegistryClient() {
  const [projectName, setProjectName] = useState("RAADHANEX Token Launch");
  const [reportId, setReportId] = useState("report_demo_001");
  const [reportHash, setReportHash] = useState("a".repeat(64));
  const [score, setScore] = useState(78);
  const [records, setRecords] = useState<any[]>([]);
  const [verifyId, setVerifyId] = useState("");
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  async function publish() { setError(null); try { const data = await apiPost<any>("/registry/publications", { project_name: projectName, report_id: reportId, report_hash: reportHash, score, risk_label: "Medium Risk - Fix Before Launch", summary: "Public metadata for a pre-audit readiness report.", status: "active", real_only_acknowledged: true }); setResult(data); setVerifyId(data.publication?.id || ""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Publish failed"); } }
  async function load() { const data = await apiGet<any>("/registry/publications"); setRecords(data.publications || []); }
  async function verify(id = verifyId) { if (!id) return; const data = await apiGet<any>(`/registry/verify/${encodeURIComponent(id)}?report_hash=${encodeURIComponent(reportHash)}`); setResult(data); }
  return <div className="quantum-module-screen mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Public Registry + Trust Badge</h1><p className="mt-4 max-w-3xl text-slate-400">Publish real report metadata with hash verification and a safe “pre-audit readiness reviewed” badge. No certified-audit or on-chain certificate claim is faked.</p><div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="card space-y-4 p-6"><label className="block text-sm font-bold text-slate-200">Project name<input className="input mt-2" value={projectName} onChange={(e) => setProjectName(e.target.value)} /></label><label className="block text-sm font-bold text-slate-200">Report ID<input className="input mt-2" value={reportId} onChange={(e) => setReportId(e.target.value)} /></label><label className="block text-sm font-bold text-slate-200">Report hash<input className="input mt-2" value={reportHash} onChange={(e) => setReportHash(e.target.value)} /></label><label className="block text-sm font-bold text-slate-200">Score<input className="input mt-2" type="number" value={score} onChange={(e) => setScore(Number(e.target.value))} /></label><div className="grid gap-3 sm:grid-cols-2"><button className="btn-primary" onClick={publish}>Publish record</button><button className="btn-secondary" onClick={load}>Load records</button></div>{error && <p className="rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}</div><div className="space-y-5"><div className="card p-6"><p className="font-black text-white">Registry records</p><div className="mt-4 space-y-3">{records.length ? records.map((r) => <div key={r.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="font-bold text-white">{r.project_name}</p><p className="text-xs text-slate-400">{r.id} • {r.status} • {r.badge_label}</p><button className="btn-secondary mt-3" onClick={() => { setVerifyId(r.id); verify(r.id); }}>Verify</button></div>) : <p className="text-sm text-slate-400">No registry records loaded.</p>}</div></div>{result && <div className="card p-6"><p className="font-black text-white">Latest result</p><div className="mt-4"><JsonBlock value={result} /></div></div>}</div></div></div>;
}
