export const brand = {
  product: "Web3Guard AI",
  company: "RAADHANEX",
  tagline: "AI-assisted Web3 launch security review before expensive professional audit.",
  disclaimer: "This is a preliminary security review and does not replace a full manual audit."
};

export const modules = [
  { key: "unified-url", title: "Unified URL Scan", href: "/scanner/unified-url", description: "Single real-only URL launch map: website live scan + optional API/Solidity/GitHub inputs, with missing modules marked Not assessed." },
  { key: "website-advanced", title: "Advanced Website", href: "/scanner/website-advanced", description: "Mega Phase B safe website launch intelligence: policy pages, Web3 keywords, visible contract addresses, API hints, scripts, and social/trust signals." },
  { key: "api-deep", title: "API Deep Readiness", href: "/scanner/api-deep", description: "Safe OpenAPI/code/notes API readiness scanner for auth, CORS, webhooks, admin routes, rate limits, and BOLA/IDOR review. No fuzzing." },
  { key: "wallet-risk", title: "Wallet Risk API", href: "/scanner/wallet-risk", description: "Optional GoPlus-powered token/approval risk lookup plus local spender/wallet context. No wallet connect, no signing, no private key collection." },
  { key: "monitoring-lite", title: "Monitoring Lite", href: "/monitoring", description: "Mega Phase C monitoring configs, manual/admin alerts, and optional read-only RPC event checks. No fake live alerts or wallet signing." },
  { key: "cicd", title: "CI/CD GitHub Action", href: "/cicd", description: "Generate real GitHub Action templates that call Web3Guard Developer API. No fake CI status, no dependency install, no private-key collection." },
  { key: "learning", title: "Learning Center", href: "/learning", description: "Hinglish/English Web3 security knowledge base with real user progress records. No fake certification." },
  { key: "admin-super", title: "Admin Super Panel", href: "/admin/super", description: "Admin-only operational dashboard from real stored records, feature flags, health snapshot, and audit logs. No fake MRR/system metrics." },
  { key: "threat-intel", title: "Threat Intel", href: "/threat-intel", description: "Manual-curated threat intelligence and local knowledge base. No fake live news feed; live sources must be explicitly enabled and cited." },
  { key: "github", title: "GitHub Repo", href: "/scanner/github", description: "Read-only public GitHub repo scanner for Solidity files, package.json, frontend/API/config/deploy hints, and secret-hygiene risks. No clone, execution, or install." },
  { key: "contract-address", title: "Contract Address", href: "/scanner/address", description: "Verified explorer source fetch for EVM addresses via Etherscan API V2-compatible flow. No private keys, no signing, no fake score if unverified." },
  { key: "permission-map", title: "Permission Map", href: "/scanner/permission-map", description: "Real source/ABI/manual-fact role map for owner, minter, pauser, upgrader, treasury, fee, freeze, and oracle powers with centralization/transparency score." },
  { key: "launch-transparency", title: "Launch Transparency", href: "/scanner/launch-transparency", description: "Token/NFT/staking/DAO/presale disclosure scanner for owner powers, mint/pause/blacklist/tax/treasury/metadata risks. No rug-pull accusation or fake proof." },
  { key: "contract-diff", title: "Contract Diff", href: "/scanner/contract-diff", description: "Compare old vs new Solidity source, show new/fixed/open risks, risky added lines, and score delta. No auto-fix or semantic proof." },
  { key: "upgrade-safety", title: "Upgrade Safety", href: "/scanner/upgrade-safety", description: "Detect UUPS/Transparent/Beacon proxy hints, initializer guards, upgrade authorization, and storage-order changes from real source." },
  { key: "static-analysis", title: "Static Analysis", href: "/scanner/static-analysis", description: "Runs real Slither/Aderyn/Semgrep only when installed and enabled. Missing tools are marked clearly; no fake static-analysis findings." },
  { key: "deep-analysis", title: "Deep Analysis", href: "/scanner/deep-analysis", description: "Runs real Mythril/Manticore/Echidna only when installed and enabled. Standard/deep mode requires ownership verification; no fake symbolic/fuzz findings." },
  { key: "contract", title: "Smart Contract", href: "/scanner/contract", description: "Solidity rule engine with score, findings, business impact, and fix direction." },
  { key: "website", title: "Website Surface", href: "/scanner/website", description: "Safe passive headers, HTTPS, robots, sitemap, and launch-surface hints." },
  { key: "dapp", title: "dApp Frontend", href: "/scanner/dapp", description: "Static hints + checklist for public secrets, hardcoded RPC/address, transaction preview, wallet UX, approvals, and dependency review." },
  { key: "api", title: "API Backend", href: "/scanner/api", description: "Static hints + checklist for CORS, auth, rate limits, webhooks, docs exposure, hardcoded secrets, and BOLA/IDOR risk." },
  { key: "wallet", title: "Wallet Flow", href: "/scanner/wallet", description: "Approval, Permit2, spender, chain mismatch, blind-signing, auto-prompt, mint/claim, and WalletConnect readiness review." },
  { key: "admin", title: "Admin OpSec", href: "/scanner/admin-opsec", description: "Multisig, timelock, role separation, upgrade admin, treasury, hardware wallet, private key policy, signer rotation, MFA, audit logs, and incident response review." }
];

export const nav = [
  { href: "/", label: "Home" },
  { href: "/scanner", label: "Scanner" },
  { href: "/scanner/unified-url", label: "URL Scan" },
  { href: "/scanner/website-advanced", label: "Web+" },
  { href: "/scanner/api-deep", label: "API+" },
  { href: "/scanner/wallet-risk", label: "Wallet API" },
  { href: "/monitoring", label: "Monitoring" },
  { href: "/threat-intel", label: "Threat Intel" },
  { href: "/scanner/github", label: "GitHub" },
  { href: "/scanner/address", label: "Address" },
  { href: "/scanner/permission-map", label: "Permissions" },
  { href: "/scanner/launch-transparency", label: "Launch Transparency" },
  { href: "/scanner/contract-diff", label: "Diff" },
  { href: "/scanner/upgrade-safety", label: "Upgrade" },
  { href: "/scanner/static-analysis", label: "Static" },
  { href: "/scanner/deep-analysis", label: "Deep" },
  { href: "/pricing", label: "Pricing" },
  { href: "/methodology", label: "Methodology" },
  { href: "/sample-reports", label: "Samples" },
  { href: "/report", label: "Report" },
  { href: "/trust", label: "Trust" },
  { href: "/ownership-verification", label: "Ownership" },
  { href: "/feature-status", label: "Status" },
  { href: "/local-qa", label: "Local QA" },
  { href: "/launch-pack", label: "Launch" },
  { href: "/auth/login", label: "Login" },
  { href: "/auth/signup", label: "Sign up" },
  { href: "/dashboard", label: "Dashboard" },
  { href: "/scope-refund", label: "Scope" },
  { href: "/contact", label: "Request Review" }
];
