import Link from "next/link";
import { ProfessionalReportClient } from "@/components/report/ProfessionalReportClient";

export default function ProfessionalReportPage() {
  return (
    <main className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
      <p className="text-sm font-black uppercase tracking-[0.3em] text-cyan">Phase 9 professional report system</p>
      <h1 className="mt-3 text-4xl font-black sm:text-6xl">Professional PDF / HTML / Public Report Delivery</h1>
      <p className="mt-5 max-w-4xl text-lg leading-8 text-slate-300">
        Generate delivery-ready artifacts from a real combined report object. The system produces server-side PDF bytes, branded HTML, Markdown, JSON, and public/private report records with hash verification. It does not fake certified audit status.
      </p>
      <div className="mt-8 grid gap-4 md:grid-cols-4">
        {[
          ["Server PDF", "Generated by backend from report data, not browser print only."],
          ["Public/Private", "Publish report records with pre-audit readiness wording."],
          ["Hash Verify", "Check public record hash against report_hash."],
          ["Real-only", "No report export without real report_id + report_hash."],
        ].map(([title, text]) => (
          <div key={title} className="card p-5">
            <p className="font-black text-white">{title}</p>
            <p className="mt-2 text-sm text-slate-400">{text}</p>
          </div>
        ))}
      </div>
      <section className="mt-8 rounded-3xl border border-amber-400/20 bg-amber-400/10 p-5 text-sm leading-6 text-amber-100">
        Public-safe wording: <strong>Pre-audit readiness reviewed by Web3Guard AI by RAADHANEX</strong>. Do not use: certified audit, 100% secure, insurance guaranteed, or exploit-proof.
      </section>
      <div className="mt-8">
        <ProfessionalReportClient />
      </div>
      <div className="mt-8 flex flex-wrap gap-3">
        <Link className="btn-primary" href="/report">Report overview</Link>
        <Link className="btn-secondary" href="/scanner">Run scanner modules</Link>
        <Link className="btn-secondary" href="/sample-reports">Sample reports</Link>
      </div>
    </main>
  );
}
