"use client";
import { useEffect, useState } from "react";
import { apiGet, apiPost } from "@/lib/api";
function JsonBlock({ value }: { value: unknown }) { return <pre className="mono max-h-96 overflow-auto rounded-2xl border border-white/10 bg-black/30 p-4 text-xs text-slate-300">{JSON.stringify(value, null, 2)}</pre>; }
export function NotificationsClient() {
  const [status, setStatus] = useState<any>(null);
  const [events, setEvents] = useState<any[]>([]);
  const [title, setTitle] = useState("Critical finding preview");
  const [message, setMessage] = useState("Web3Guard AI found a high-priority launch readiness issue. Please review dashboard findings.");
  const [email, setEmail] = useState("");
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  async function load() { setError(null); try { const [s, e] = await Promise.all([apiGet<any>("/notifications/status"), apiGet<any>("/notifications/events")]); setStatus(s); setEvents(e.events || []); } catch(err) { setError(err instanceof Error ? err.message : "Notification load failed"); } }
  async function sendPreview() { setError(null); try { const data = await apiPost<any>("/notifications/send", { event_type: "critical_finding", channels: [email ? "email" : "manual"], title, message, severity: "high", recipient_email: email || null, dry_run: true, real_only_acknowledged: true }); setResult(data); await load(); } catch(err) { setError(err instanceof Error ? err.message : "Notification send failed"); } }
  useEffect(() => { load(); }, []);
  return <div className="quantum-module-screen mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.3em] text-cyan">Web3Guard AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Notifications Center</h1><p className="mt-4 max-w-3xl text-slate-400">Real notification records with provider-gated delivery. Email/Telegram/Discord/WhatsApp are only marked sent when a real provider is configured and accepts delivery. Default is dry-run/manual preview.</p>{error && <p className="mt-6 rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="card p-5 space-y-4"><p className="text-xl font-black text-white">Send dry-run preview</p><label className="block text-sm text-slate-300">Title<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={title} onChange={e=>setTitle(e.target.value)} /></label><label className="block text-sm text-slate-300">Message<textarea className="mt-2 h-28 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={message} onChange={e=>setMessage(e.target.value)} /></label><label className="block text-sm text-slate-300">Recipient email optional<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 p-3 text-white" value={email} onChange={e=>setEmail(e.target.value)} /></label><button onClick={sendPreview} className="btn-primary w-full">Create notification preview</button><p className="text-xs text-slate-500">This uses dry_run=true, so no fake provider delivery is claimed.</p></div><div className="space-y-5"><div className="card p-5"><p className="font-black text-white">Provider status</p>{status ? <JsonBlock value={status} /> : <p className="text-slate-400">Loading...</p>}</div>{result && <div className="card p-5"><p className="font-black text-white">Latest event</p><JsonBlock value={result} /></div>}<div className="card p-5"><p className="font-black text-white">Stored events</p><JsonBlock value={events} /></div></div></div></div>;
}
